---
- name: Ansible blocks 2
  hosts: rhelserver
  gather_facts: false

  tasks:
  - block:
    - name: list home dir content
      command: "ls -l ~/"

    - name: list root partition content
      command: "ls -l /root/"
      register: root_error
   
    rescue:
      - name: run when failure occurs in block [rescue block]
        debug:
          msg: 
            - "Error occurred in block section"
            - "{{ root_error.stdout }}"
            - "{{ root_error.stderr }}"

    always:
      - name: always run
        debug:
          msg: "entered in always block"
      - name: list root partition content with become
        command: "ls -l /root/"
        become: yes
        #when: 1 == 1
        when: root_error.stderr | regex_search("Permission denied")

      - name: list root partition content with become
        command: "ls -l /root/"
        become: yes
        #when: 1 == 2
        when: root_error.stderr | regex_search("Permission denied.....")