---
- name: install vsftpd - use block, rescue, always
  hosts: centosserver
  gather_facts: false
  become: yes
  vars:
    anonymous_enable: yes
    local_enable: yes
    write_enable: yes
    anon_upload_enable: yes

  tasks:
  - block:
    - name: Install vsftpd using yum module
      yum:
        name: vsftpd
        state: latest
    
    - name: take backup of existing config
      copy:
        src: /etc/vsftpd/vsftpd.conf
        dest: /etc/vsftpd/vsftpd.conf.bkp
        remote_src: yes

    - name: copy the config file from controller to managed node
      template:
        src: /base/roles/vsftpd/templates/vsftpd.j2
        dest: /etc/vsftpd/vsftpd.conf

    - name: this will failure
      command: "ls -l /etc/jagadeesh/"

    rescue:
      - name: print a msg 
        debug: 
          msg: "enter into rescue block"
      
      - name: recover the conf file from backup
        copy:
          src: /etc/vsftpd/vsftpd.conf.bkp
          dest: /etc/vsftpd/vsftpd.conf
          remote_src: yes
          
    always:
      - name: vsftpd restart
        service:
          name: vsftpd
          state: restarted     

