# blocks sample
---
- name: Ansible blocks
  hosts: rhelserver
  gather_facts: false

  tasks:
    - block:
      - name: list usr directory contents
        command: "ls -l /usr/"
      
      - name: list root partition content
        command: "ls -l /root/"
            
      - name: list bin directory content 
        command: "ls -l /bin/"
      #become: yes

    - name: list ansible user's home dir content 
      command: "ls -l ~/"

  
