---

- name: create apache host
#  hosts: ubuntuserver
  hosts: rhelserver
  become: true

  roles:
     - vhost

  post_tasks:
     - name: install contents from local file
       copy:
         src: files/html/
         dest: "/var/www/vhosts/{{ ansible_hostname }}"
       changed_when: true
       notify: restart_httpd


