---
- name: get all instances info
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: get ec2 instance info
    ec2_instance_info:
      region: ap-south-1
    register: inst_info

  - name: print the instances
    debug:
      msg: "{{ inst_info.instance_id }}"