---
- name: Working with AWS ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: create ec2 instance
    ec2:
      instance_type: t2.micro
      image: ami-05c8ca4485f8b138a
      count: 1
      key_name: ssh-1
      group: launch-wizard-1
      region: ap-south-1

